services:
  mongo:
    image: mongo:latest
    container_name: mongo-eload
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_eload:/data/db
      - mongo_config_eload:/data/configdb

  backend:
    build: .
    container_name: eload-back
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://mongo:27017/eload_db
    depends_on:
      - mongo

  frontend:
    build: ../e-load-front-2.0
    container_name: eload-front
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_URL_API=http://localhost:8000/
    depends_on:
      - backend

volumes:
  mongo_data_eload:
  mongo_config_eload: